# Generated by Django 4.0.5 on 2022-06-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tranees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('userName', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
